#工作流的名称
name: build and deploy

#触发工作流的事件
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    #运行在Ubuntu最新版的镜像上运行
    runs-on: ubuntu-latest

    steps:
        #检查并拉取代码（保留提交历史用于 lastUpdated）
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
        #设置 Node.js 版本并启用 npm 缓存
      - name: Use Node.js 18.17.1
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '18.17.1'
          cache: npm
          
        #安装依赖（可重复构建）
      - name: Install dependencies
        run: npm ci
        
      - name: Build Project
        run: npm run docs:build
        
        #将文件上传至云服务器  

      - name: ssh-scp-deploy
        uses: marcodallasanta/ssh-scp-deploy@v1.2.0
        with:
          #本地打包后的文件目录
          local: 'docs/.vitepress/dist'
          #上传至远程服务器的目标目录
          remote: '/www/wwwroot/www.lzzftt.icu'  
          #远程服务器的地址
          host: ${{ secrets.REMOTE_HOST }}
          #远程服务器的用户名
          user: ${{ secrets.USER_NAME }}
          #远程服务器的密钥（与密码二者选其一）
          key: ${{ secrets.SSH_KEY }}
          port: 22
          
