#工作流的名称
name: build and deploy

#触发工作流的事件
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    #运行在Ubuntu最新版的镜像上运行
    runs-on: ubuntu-latest

    steps:
        #检查并拉取代码
      - name: Checkout
        uses: actions/checkout@v3
        
        #设置环境为nodejs 18
      - name: Use Node.js 18
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '18.x'
          
        #安装模块并打包项目 
      - name: install dep
        run: npm install
        
      - name: Build Project
        run: npm run docs:build
        
        #将文件上传至云服务器  
      - name: ssh-scp-deploy
        uses: appleboy/scp-action@master
        with:
          #本地打包后的文件目录
          local: docs/.vitepress/dist
          #上传至远程服务器的目标目录
          remote: /www/wwwroot/www.lzzftt.icu/dist
          #远程服务器的地址
          host: ${{ secrets.REMOTE_HOST }}
          #远程服务器的用户名
          username: ${{ secrets.USER_NAME }}
          #远程服务器的密钥（与密码二者选其一）
          key: ${{ secrets.SSH_KEY }}
          #上传后执行的脚本
          #post_upload: sudo nginx -s reload
          port: 22
          #source: "docs/.vitepress/dist"
          
          source: ""
          target: "/www/wwwroot/www.lzzftt.icu/dist"
          

